### ISSUE TITLE
Zasilkovna pickup place - weird UX when no place is found

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/demoshop#11]
### What is happening
In 2nd step of order when I choose Zasilkovna pickup place and nothing is found for my entry in the popup window, I am not notified in any way that no pickup place was found. 

It seems weird for me from UX point of view - I enter a phrase, click on "search" and nothing happens at all.
![image](https://user-images.githubusercontent.com/10401898/44025136-86692176-9eef-11e8-9784-9da0d7a37bae.png)

### Expected result
I would appreciate any kind of info message that would tell me that no pickup place was found for my search term.

**Comment by kulincz** [comment]
Yes, there should be some info. Please implement it and then I can style this info message.

**Comment by LukasHeinz** [comment]
The zasilkovna changed the integration and this way of integration is not supported anymore. Now it is necessary to implement a differnt solution for pickup place picker.

For more info please see #58 

This issue is not relevant anymore.
