### ISSUE TITLE
Zasilkovna pickup place – still visible box and weird UX when is place selected

### ISSUE THREAD

**Issue by kulincz** [shopsys/demoshop#14]
### What is happening
- Selected place in label has no active class and I can't style it than

Now I temporary fix it by CSS in pick-up-place.less: on lines 54 and 41 (display none / block when is label active)

There you can see commented video where I see some other UX troubles that can't be easily specified. There are no critical buggies.
https://www.useloom.com/share/80d7ad24d3824e759c0fec00a7ef91ca

### Expected result
- Selected place in label could has active class for styling purpose
- Or maybe batter solution: Markup can load to label after place is selected

**Comment by LukasHeinz** [comment]
@vitek-rostislav Please help me to run a cron to fiil up zasilkovna data :-) Thx

**Comment by vitek-rostislav** [comment]
@LukasHeinz Hi, I have added the cron into build of both `lh-design-freeze` and `jk-frontend-redesign` so now you have the pickup points available on these instances. Please, let us know what to do here.

**Comment by LukasHeinz** [comment]
The zasilkovna changed the integration and this way of integration is not supported anymore. Now it is necessary to implement a differnt solution for pickup place picker.

For more info please see #58 

This issue is not relevant anymore.
