### ISSUE TITLE
2. step of order doesn't found

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/demoshop#17]
### What is happening
When I want go from basket to shipping and payment page doesn't work.

### Expected result

I need to fix the page in order to go through the order

**Comment by boris-brtan** [comment]
During phing target build new there are invalid records in table setting_values all NULL values with type `integer` should have type `none` especially keys with *Id suffix so admin will be able for example to edit `/admin/legal-conditions/setting/` with items that are not set.

NULL --integer-- > 0 not expected value  
NULL --none--> null expected value

**Comment by boris-brtan** [comment]
will be released in beta2 version
