### ISSUE TITLE
PickUpPlaceController::autocompleteAction fails on non existing method getAllOnCurrentDomain

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/demoshop#42]
### What is happening

seems like during upgrade to beta6, some instructions were not applied from [shopsys/shopsys#762]
`getAllOnCurrentDomain` -> `getAllEnabledOnCurrentDomain` in `PickUpPlaceController`

### Expected result

to have autocomplete action updated and working

**Comment by boris-brtan** [comment]
is there possibility to have non-existed method calls checked by some standards or phpstan?

**Comment by PetrHeinz** [comment]
Duplicate of #41

**Comment by boris-brtan** [comment]
i see now
