### ISSUE TITLE
Registration: Error message is jumped aside

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/demoshop#61]
### What is happening
Front end -> Registration: Error message is jumped aside.
![image](https://user-images.githubusercontent.com/43062403/62926776-761f3e00-bdb5-11e9-96db-eff00fa30098.png)

### Expected result
Please fix it.

**Comment by LukasHeinz** [comment]
This issue is duplicate of #54 therefore I am closing it.

@PetraPiprekova before creating a new issue, please check if it hasn't been reported yet. Thank you.
