### ISSUE TITLE
Administrator cannot log out

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/demoshop#74]
### What is happening
After implementation of #68 the log out function for any administrator doesn't work - it doesn't do anything.

### Expected result
When I am logged as universal administrator and I click to log out, I should get logged out (redirect to admin login page). All other users logged as this admin should remain logged.

**Comment by PetrHeinz** [comment]
Cannot reproduce on current `master` (63265c615b7401bf7333c01fc5eca41602cb6f9d):

I log in as `admin`
![image](https://user-images.githubusercontent.com/10008612/64011541-2ca45200-cb1c-11e9-8271-4392bc14b5e2.png)

I get redirected to the Dashboard
![image](https://user-images.githubusercontent.com/10008612/64011586-45ad0300-cb1c-11e9-9456-4e2b34ae1b12.png)

I click on *Log out*
![image](https://user-images.githubusercontent.com/10008612/64011613-59586980-cb1c-11e9-8805-93701245ab25.png)

I am logged out and redirected to the Login page
![image](https://user-images.githubusercontent.com/10008612/64011663-7725ce80-cb1c-11e9-8dd9-98685176cb75.png)

**Comment by LukasHeinz** [comment]
The bug doesn't occur any more...
